Write-Host "This script documents the comparison between:"
Write-Host "- Microsoft 365 Direct Send (MX, Port 25)"
Write-Host "- SMTP Submission (smtp.office365.com, Port 587)"
Write-Host ""
Write-Host "Use this alongside documented test results."
Write-Host ""
Write-Host "Expected outcome:"
Write-Host "- MX may fail due to IP reputation at RCPT TO"
Write-Host "- SMTP AUTH should succeed when credentials are valid"
